booking_feature/urls.py
from django.urls import path
from .views import *
from utilities.decorators import ownership_required
from booking_feature.models import BoardingHouse, Room

# Define the lambda function to get the BoardingHouse object
get_boarding_house = lambda request, *args, **kwargs: BoardingHouse.objects.get(id=kwargs['boarding_house_id']) # kwargs['boarding_house_id'] is the value of the keyword argument in the URL pattern

# Define the lambda function to get the BoardingHouse object from the Room object
get_boarding_house_from_room = lambda request, *args, **kwargs: Room.objects.get(id=kwargs['room_id']).boarding_house_id

urlpatterns = [
    path('boarding-house/create/', BoardingHouseCreateView.as_view(), name='add_boarding_house'),
    path('boarding-house/<uuid:boarding_house_id>/edit/', ownership_required(
            get_boarding_house, 
            owner_field='account_id', 
            redirect_url='/', 
            allow_superuser=True
        )(BoardingHouseUpdateView.as_view()), name='edit_boarding_house'),
    path('boarding-house/<uuid:boarding_house_id>/', BoardingHouseDetailView.as_view(), name='boarding_house_detail'),
    path('boarding-house/list', BoardingHouseListView.as_view(), name='boarding_house_list'),
    path('boarding-house/<uuid:boarding_house_id>/delete/', ownership_required(
             get_boarding_house, 
             owner_field='account_id', 
             redirect_url='/',
             allow_superuser=True
         )(BoardingHouseDeleteView.as_view()), name='delete_boarding_house'),

    path('boarding_house/<uuid:boarding_house_id>/room/list', RoomListView.as_view(), name='room_list'),
    path('boarding_house/<uuid:boarding_house_id>/room/add', ownership_required(
             get_boarding_house, 
             owner_field='account_id', 
             redirect_url='/',
             allow_superuser=True
         )(RoomCreateView.as_view()), name='add_room'),
    path('room/<uuid:room_id>/edit', ownership_required(
             get_boarding_house_from_room, 
             owner_field='account_id', 
             redirect_url='/',
             allow_superuser=True
         )(RoomUpdateView.as_view()), name='edit_room'),
    path('room/<uuid:room_id>/', RoomDetailView.as_view(), name='room_detail'),
    path('room/<uuid:room_id>/delete/', ownership_required(
             get_boarding_house_from_room, 
             owner_field='account_id', 
             redirect_url='/',
             allow_superuser=True
         )(RoomDeleteView.as_view()), name='delete_room'),
]

features/authentication/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from . import views
from utilities.decorators import anonymous_required

app_name = "authentication"

# TODO: Secure Endpoints
urlpatterns = [
    path("register/", anonymous_required(views.RegistrationWizard.as_view()), name="register"),
    path("login/", anonymous_required(views.LoginView.as_view()), name="login"),
    path("logout/", login_required(views.LogoutView.as_view()), name="logout"),
    path("", views.home, name="home"),
    path("profile/<int:pk>/", views.ProfileView.as_view(), name="profile"),
    path("profile/<str:username>/", views.ProfileView.as_view(), name="profile-by-username"),
    path("profile/", views.ProfileView.as_view(), name="my-profile"),
    path("change-password/", login_required(views.ChangePasswordView.as_view()), name="change-password"),
    path("profile/edit", login_required(views.EditProfileView.as_view()), name="edit-profile"),
    path("additional-info/", login_required(views.AdditionalInfoView.as_view()), name="personal-information"),
]

features/property_management/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from . import views

app_name = "property_management"

# TODO: Secure Endpoints
urlpatterns = [
    path("dashboard/booking-management/", login_required(views.BookingListView.as_view()), name="booking-management"),
    path("dashboard/booking-management/bookings/", login_required(views.BookingListView.as_view()),
         name="dashboard-bookings"),
    path("dashboard/booking-management/booking/<int:pk>/", login_required(views.BookingDetailView.as_view()), name="booking"),

    path("dashboard/property-management/", login_required(views.BoardingHouseListView.as_view()),
         name="dashboard"),
    path("dashboard/property-management/boarding-houses/", login_required(views.BoardingHouseListView.as_view()),
         name="dashboard-boarding-houses"),
    path("dashboard/property-management/boarding-rooms/", login_required(views.BoardingRoomListView.as_view()),
         name="dashboard-boarding-rooms"),

    path("dashboard/property-management/boarding-houses/create/", login_required(views.BoardingHouseCreateView.as_view()),
         name="create-boarding-house"),
    path("dashboard/property-management/boarding-house/<int:pk>/edit", login_required(views.BoardingHouseUpdateView.as_view()),
         name="update-boarding-house"),

    path("dashboard/property-management/boarding-rooms/create/", login_required(views.BoardingRoomCreateView.as_view()),
         name="create-boarding-room"),
    path("dashboard/property-management/boarding-room/<int:pk>/edit", login_required(views.BoardingRoomUpdateView.as_view()),
         name="update-boarding-room"),

    path("dashboard/tenant-management/", login_required(views.RoomTenantListView.as_view()), name="tenant-management"),
    path("dashboard/tenant-management/<str:tenant_status>/", login_required(views.RoomTenantListView.as_view()),
         name="dashboard-tenants"),

    path("landlords/", views.LandlordListView.as_view(), name="landlords"),
    path("rent-a-room/", views.RentARoomListView.as_view(), name="rent-a-room"),

    path("boarding-room/<int:pk>/", views.BoardingRoomDetailView.as_view(), name="boarding-room"),
    path("boarding-house/<int:pk>/", views.BoardingHouseDetailView.as_view(), name="boarding-house"),
]

huntify_main_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication_feature.urls')),
]

huntify_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

from features.authentication.views import UpdateProfileView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("test/", UpdateProfileView.as_view(), name="test"),
    path("", include("features.authentication.urls")),
    path("", include("features.property_management.urls")),
    path("", include("features.address.urls")),
    path("", include("features.notification.urls")),
    path("__reload__/", include("django_browser_reload.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

templates/html/base.html
{% load static tailwind_tags %}
<!doctype html>
<html lang="en" class="!scroll-smooth">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Huntify{% endblock %}</title>
    {% tailwind_css %}
    <link rel="stylesheet" href="{% static 'fontawesome/css/all.min.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lora:wght@400;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Merriweather:wght@400;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;600;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@400;500;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@400;600&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@400;600;700&display=swap" rel="stylesheet">
</head>
<body class="animate-fadeIn">
{% block content %}{% endblock %}
<script src="{% static 'node_modules/flowbite/dist/flowbite.min.js' %}"></script>
</body>
</html>

templates/html/footer.html
{% load static %}

<footer class="bg-white rounded-lg shadow-md m-4 px-6 py-3">
    <div class="max-w-screen-xl mx-auto p-4 md:py-8">
        <div class="flex flex-wrap justify-between items-center">
            <!-- Logo and Brand Name -->
            <a href="https://flowbite.com/" class="flex items-center space-x-3 rtl:space-x-reverse mb-4 sm:mb-0">
                <img src="{% static 'images/logo1.png' %}" alt="Logo" class="h-12 object-contain" />
                <span class="text-2xl font-semibold text-black">HUNTIFY</span>
            </a>

            <!-- Navigation Links -->
            <ul class="flex flex-wrap items-center text-sm font-medium text-gray-500 dark:text-gray-400 space-x-4 sm:space-x-6">
                <li>
                    <a href="#" class="hover:underline">About</a>
                </li>
                <li>
                    <a href="#" class="hover:underline">Privacy Policy</a>
                </li>
                <li>
                    <a href="#" class="hover:underline">Licensing</a>
                </li>
                <li>
                    <a href="#" class="hover:underline">Contact</a>
                </li>
            </ul>
        </div>

        <!-- Horizontal Divider -->
        <hr class="my-6 border-gray-200 dark:border-gray-700" />

        <!-- Footer Copyright -->
        <div class="text-sm text-gray-500 dark:text-gray-400 text-center">
            <span>© 2024 <a href="https://flowbite.com/" class="hover:underline">Huntify</a>. All Rights Reserved.</span>
        </div>
    </div>
</footer>

templates/html/form_tester.html
{{ form.as_p }}

templates/html/header.html
{% load static %} {% load custom_tag %}

<header>
  <nav
    class="fixed top-0 z-50 w-full border-b border-gray-200 bg-white dark:border-gray-600"
    role="navigation"
  >
    <div
      class="container mx-auto flex flex-wrap items-center justify-between px-6 py-3"
    >
      <!-- Logo -->
      <a href="#" class="flex items-center space-x-3">
        <div class="p-2">
          <img
            src="{% static 'images/logo1.png' %}"
            alt="Logo"
            class="h-12 object-contain"
          />
        </div>
      </a>

      <!-- Navigation Links -->
      <div
        id="menu"
        class="hidden w-full flex-col md:flex md:w-auto md:flex-row md:items-center"
      >
        <ul
          class="flex flex-col space-y-2 md:flex-row md:space-x-8 md:space-y-0"
        >
          <li>
            <a
              href="{% url 'authentication:home' %}"
              class="font-['Plus Jakarta Sans'] {% if request.resolver_match.url_name == 'home' %}text-gray-700{% endif %} block px-4 py-2 text-base font-medium text-[#1f7a76] hover:text-gray-700"
            >
              Home
            </a>
          </li>

          <li>
            <a
              href="{% url 'authentication:home' %}#about"
              class="font-['Plus Jakarta Sans'] {% if request.resolver_match.url_name == 'about' %}text-gray-700{% endif %} block px-4 py-2 text-base font-medium text-[#1f7a76] hover:text-gray-700"
            >
              About Us
            </a>
          </li>

          <li>
            <a
              href="{% url 'property_management:landlords' %}"
              class="font-['Plus Jakarta Sans'] {% if request.resolver_match.url_name == 'landlords' %}text-gray-700{% endif %} block px-4 py-2 text-base font-medium text-[#1f7a76] hover:text-gray-700"
            >
              Landlords
            </a>
          </li>

        </ul>
      </div>

      <!-- Action Buttons -->
      <div class="flex items-center space-x-5">
        {% if user.is_authenticated %}
        <!-- Notification Button -->
        <div class="flex items-center">
          <button
            type="button"
            id="notification-menu-button"
            aria-expanded="false"
            data-dropdown-toggle="notification-dropdown"
            data-dropdown-placement="bottom"
            class="relative flex h-12 w-12 items-center justify-center"
          >
            <span class="sr-only">Open notification menu</span>
            <!-- prettier-ignore -->
            {% call_method 'notification.Notification' 'get_user_unread_notifications' request.user as notifications %}
            {% if notifications %}
            <div
              class="absolute -end-2 -top-2 inline-flex h-6 w-6 items-center justify-center rounded-full border-2 bg-red-500 text-xs font-bold text-white"
            >
              {{ notifications.count }}
            </div>
            {% endif %}
            <i
              class="fa-solid fa-bell text-2xl hover:text-gray-700"
            ></i>
          </button>
          <div
            class="z-50 my-2 hidden list-none divide-y divide-gray-100 rounded-lg bg-white text-base shadow dark:divide-gray-600 dark:bg-gray-700"
            id="notification-dropdown"
          >
            <ul class="flex flex-col items-center"></ul>
            <div class="flex">
              <a
                href="{% url 'authentication:my-profile' %}?tab=notifications"
                class="mx-auto p-3 text-sm font-medium text-[#1f7a76] hover:underline"
                >View All</a
              >
            </div>
            <script
              type="module"
              src="{% static 'js/notification.js' %}"
            ></script>
          </div>
        </div>

        <!-- Profile Menu -->
        <div class="relative">
          <button
            type="button"
            id="user-menu-button"
            class="flex items-center"
            aria-expanded="false"
            data-dropdown-toggle="user-dropdown"
          >
            <span class="sr-only">Open user menu</span>
            <img
              class="h-10 w-10 rounded-full object-cover"
              src="{{ user.avatar }}"
              alt="{{ user.username }}"
            />
          </button>
          <div
            id="user-dropdown"
            class="absolute right-0 z-50 mt-2 hidden w-48 rounded-md bg-white shadow-lg dark:divide-gray-600 dark:bg-gray-700"
          >
            <div class="px-4 py-3">
              <span class="block text-sm text-[#1f7a76]">{{ user.username }}</span>
              <span class="block truncate text-sm text-gray-500">{{ user.email }}</span>
            </div>
            <ul class="py-2">
              <li>
                <a
                  href="{{ user.get_absolute_url }}"
                  class="block px-4 py-2 text-sm text-[#1f7a76] hover:bg-gray-100"
                >
                  Profile
                </a>
              </li>
              {% if user.user_type == 'landlord' %}
              <li>
                <a
                  href="{% url 'property_management:dashboard' %}"
                  class="block px-4 py-2 text-sm text-[#1f7a76] hover:bg-gray-100"
                >
                  Dashboard
                </a>
              </li>
              {% endif %}
              <li>
                <form method="POST" action="{% url 'authentication:logout' %}">
                  {% csrf_token %}
                  <button
                    type="submit"
                    class="w-full px-4 py-2 text-left text-sm text-red-600 hover:bg-gray-100"
                  >
                    Sign out
                  </button>
                </form>
              </li>
            </ul>
          </div>
        </div>
        {% else %}
        <a
          href="{% url 'authentication:login' %}"
          class="flex h-9 w-32 items-center justify-center rounded-lg bg-[#369e98] px-3 py-1 text-sm font-medium text-white hover:bg-[#317d74]"
        >
          Sign In
        </a>
        {% endif %}

        <!-- Rent a Room Button -->
        <a
          href="{% url 'property_management:rent-a-room' %}"
          class="flex h-9 w-32 items-center justify-center rounded-lg border border-gray-300 bg-white px-3 py-1 text-center text-sm font-medium text-[#1f7a76] hover:border-gray-400 hover:bg-gray-100"
        >
          Rent a Room
        </a>

        <!-- Hamburger Menu Button (Moved) -->
        <div class="relative md:hidden">
          <button
            type="button"
            class="inline-flex items-center justify-center rounded-md p-2 text-[#1f7a76] hover:text-gray-200 dark:hover:bg-gray-700"
            aria-controls="hamburger-menu"
            aria-expanded="false"
          >
            <span class="sr-only">Open main menu</span>
            <svg
              class="h-6 w-6"
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
              aria-hidden="true"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="M4 6h16M4 12h16m-7 6h7"
              ></path>
            </svg>
          </button>

          <!-- Hamburger Menu Dropdown -->
          <div
            id="hamburger-menu"
            class="absolute right-0 z-50 mt-2 hidden w-48 rounded-md bg-white shadow-lg dark:divide-gray-600 dark:bg-gray-700"
          >
            <ul class="flex flex-col space-y-2">
              <li>
                <a
                  href="{% url 'authentication:home' %}"
                  class="block px-4 py-2 text-base font-medium text-[#1f7a76] hover:text-gray-200"
                >
                  Home
                </a>
              </li>

              <li>
                <a
                  href="{% url 'property_management:landlords' %}"
                  class="block px-4 py-2 text-base font-medium text-[#1f7a76] hover:text-gray-200"
                >
                  Landlord
                </a>
              </li>
              <li>
                <a
                  href="{% url 'authentication:home' %}#about"
                  class="block px-4 py-2 text-base font-medium text-[#1f7a76] hover:text-gray-200"
                >
                  About Us
                </a>
              </li>

            </ul>
          </div>
        </div>
      </div>
    </div>
  </nav>
</header>

<script>
  const hamburgerButton = document.querySelector(
    'button[aria-controls="hamburger-menu"]',
  );
  const dropdownMenu = document.getElementById("hamburger-menu");
  hamburgerButton.addEventListener("click", () => {
    dropdownMenu.classList.toggle("hidden");
  });
</script>