booking_feature/urls.py
from django.urls import path
from .views import *
from utilities.decorators import ownership_required
from booking_feature.models import BoardingHouse, Room

# Define the lambda function to get the BoardingHouse object
get_boarding_house = lambda request, *args, **kwargs: BoardingHouse.objects.get(id=kwargs['boarding_house_id']) # kwargs['boarding_house_id'] is the value of the keyword argument in the URL pattern

# Define the lambda function to get the BoardingHouse object from the Room object
get_boarding_house_from_room = lambda request, *args, **kwargs: Room.objects.get(id=kwargs['room_id']).boarding_house_id

urlpatterns = [
    path('boarding-house/create/', BoardingHouseCreateView.as_view(), name='add_boarding_house'),
    path('boarding-house/<uuid:boarding_house_id>/edit/', ownership_required(
            get_boarding_house, 
            owner_field='account_id', 
            redirect_url='/', 
            allow_superuser=True
        )(BoardingHouseUpdateView.as_view()), name='edit_boarding_house'),
    path('boarding-house/<uuid:boarding_house_id>/', BoardingHouseDetailView.as_view(), name='boarding_house_detail'),
    path('boarding-house/list', BoardingHouseListView.as_view(), name='boarding_house_list'),
    path('boarding-house/<uuid:boarding_house_id>/delete/', ownership_required(
             get_boarding_house, 
             owner_field='account_id', 
             redirect_url='/',
             allow_superuser=True
         )(BoardingHouseDeleteView.as_view()), name='delete_boarding_house'),

    path('boarding_house/<uuid:boarding_house_id>/room/list', RoomListView.as_view(), name='room_list'),
    path('boarding_house/<uuid:boarding_house_id>/room/add', ownership_required(
             get_boarding_house, 
             owner_field='account_id', 
             redirect_url='/',
             allow_superuser=True
         )(RoomCreateView.as_view()), name='add_room'),
    path('room/<uuid:room_id>/edit', ownership_required(
             get_boarding_house_from_room, 
             owner_field='account_id', 
             redirect_url='/',
             allow_superuser=True
         )(RoomUpdateView.as_view()), name='edit_room'),
    path('room/<uuid:room_id>/', RoomDetailView.as_view(), name='room_detail'),
    path('room/<uuid:room_id>/delete/', ownership_required(
             get_boarding_house_from_room, 
             owner_field='account_id', 
             redirect_url='/',
             allow_superuser=True
         )(RoomDeleteView.as_view()), name='delete_room'),
]

features/property_management/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from . import views

app_name = "property_management"

# TODO: Secure Endpoints
urlpatterns = [
    path("dashboard/booking-management/", login_required(views.BookingListView.as_view()), name="booking-management"),
    path("dashboard/booking-management/bookings/", login_required(views.BookingListView.as_view()),
         name="dashboard-bookings"),
    path("dashboard/booking-management/booking/<int:pk>/", login_required(views.BookingDetailView.as_view()), name="booking"),

    path("dashboard/property-management/", login_required(views.BoardingHouseListView.as_view()),
         name="dashboard"),
    path("dashboard/property-management/boarding-houses/", login_required(views.BoardingHouseListView.as_view()),
         name="dashboard-boarding-houses"),
    path("dashboard/property-management/boarding-rooms/", login_required(views.BoardingRoomListView.as_view()),
         name="dashboard-boarding-rooms"),

    path("dashboard/property-management/boarding-houses/create/", login_required(views.BoardingHouseCreateView.as_view()),
         name="create-boarding-house"),
    path("dashboard/property-management/boarding-house/<int:pk>/edit", login_required(views.BoardingHouseUpdateView.as_view()),
         name="update-boarding-house"),

    path("dashboard/property-management/boarding-rooms/create/", login_required(views.BoardingRoomCreateView.as_view()),
         name="create-boarding-room"),
    path("dashboard/property-management/boarding-room/<int:pk>/edit", login_required(views.BoardingRoomUpdateView.as_view()),
         name="update-boarding-room"),

    path("dashboard/tenant-management/", login_required(views.RoomTenantListView.as_view()), name="tenant-management"),
    path("dashboard/tenant-management/<str:tenant_status>/", login_required(views.RoomTenantListView.as_view()),
         name="dashboard-tenants"),

    path("landlords/", views.LandlordListView.as_view(), name="landlords"),
    path("rent-a-room/", views.RentARoomListView.as_view(), name="rent-a-room"),

    path("boarding-room/<int:pk>/", views.BoardingRoomDetailView.as_view(), name="boarding-room"),
    path("boarding-house/<int:pk>/", views.BoardingHouseDetailView.as_view(), name="boarding-house"),
]

huntify_main_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication_feature.urls')),
]

huntify_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

from features.authentication.views import UpdateProfileView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("test/", UpdateProfileView.as_view(), name="test"),
    path("", include("features.authentication.urls")),
    path("", include("features.property_management.urls")),
    path("", include("features.address.urls")),
    path("", include("features.notification.urls")),
    path("__reload__/", include("django_browser_reload.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

features/property_management/views.py
from django.contrib import messages
from django.core.paginator import EmptyPage, Paginator
from django.db import transaction
from django.db.models import Count, Q, Value
from django.db.models.functions import Concat
from django.http import HttpResponseForbidden, HttpResponseRedirect
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy
from django.utils import timezone
from django.views.generic import ListView, DetailView, CreateView, UpdateView

from features.authentication.models import User
from features.property_management.forms import CreateBoardingHouseForm, CreateBoardingRoomForm, BoardingHouseSearchForm, \
    BoardingRoomSearchForm, RequestBookingForm, BookingSearchForm, UpdateBoardingHouseForm, UpdateBoardingRoomForm, \
    RoomTenantSearchForm
from features.property_management.models import BoardingHouse, BoardingRoom, Tag, Booking, BoardingRoomTenant
from features.rating.forms import RatingForm
from features.notification.utils import create_notification


# Create your views here.
# Safe Paginator where it can handle cases where the user tries to access a page that does not exist
class SafePaginator(Paginator):
    def validate_number(self, number):
        try:
            return super().validate_number(number)
        except EmptyPage:
            if number > 1:
                return self.num_pages
            else:
                raise


# TODO: Restrict access to these views to landlords only
# OPTIMIZE: BoardingHouseListView and BoardingRoomListView can be refactored possibly through mixins or inheritance
class BoardingHouseListView(ListView):
    model = BoardingHouse
    paginator_class = SafePaginator
    context_object_name = 'boarding_houses'
    paginate_by = 10
    template_name = 'property_management/dashboard/property/boarding_house/boarding_house_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['total_boarding_houses'] = self.get_queryset().count()
        context['search_form'] = BoardingHouseSearchForm(self.request.GET)

        context['create_boarding_house_form'] = CreateBoardingHouseForm(landlord=self.request.user)
        context['create_boarding_room_form'] = CreateBoardingRoomForm(landlord=self.request.user)

        return context

    def get_queryset(self):
        queryset = super().get_queryset().order_by('-created_at')

        queryset = queryset.filter(landlord=self.request.user)
        # Handle search query
        query = self.request.GET.get('query', '')
        search_by = self.request.GET.get('search_by', 'name')  # Default to 'name' if not specified
        if query:
            if search_by == 'name':
                queryset = queryset.filter(name__icontains=query)
            elif search_by == 'location':
                queryset = queryset.annotate(
                    location=Concat(
                        'barangay__name', Value(', '),
                        'municipality__name', Value(', '),
                        'province__name'
                    )
                ).filter(location__icontains=query)

        # Handle sorting with direction (ascending or descending)
        sort_by = self.request.GET.get('sort', '')
        direction = self.request.GET.get('direction', 'asc')  # Default direction is ascending
        if sort_by:
            if sort_by == 'name':
                queryset = queryset.order_by(f"{'-' if direction == 'desc' else ''}name")
            elif sort_by == 'available_rooms':
                queryset = queryset.annotate(
                    available_rooms=Count('rooms', filter=Q(rooms__is_available=True))
                ).order_by(f"{'-' if direction == 'desc' else ''}available_rooms")
            elif sort_by == 'created_at':
                queryset = queryset.order_by(f"{'-' if direction == 'desc' else ''}created_at")

        return queryset

    def post(self, request, *args, **kwargs):
        self.object_list = self.get_queryset()
        context = self.get_context_data()

        # Handle deletion of a boarding house
        if 'delete-boarding_house' in request.POST:
            boarding_house_id = request.POST.get('delete-boarding_house')
            boarding_house = get_object_or_404(BoardingHouse, id=boarding_house_id)

            # Ensure only authorized users can delete
            if boarding_house.landlord != request.user:
                return HttpResponseForbidden("You are not allowed to delete this item.")

            messages.success(request, "Boarding house deleted successfully.")
            # Delete the boarding house
            boarding_house.delete()

        return self.render_to_response(context)


class BoardingRoomListView(ListView):
    model = BoardingRoom
    paginator_class = SafePaginator
    context_object_name = 'boarding_rooms'
    paginate_by = 10
    template_name = 'property_management/dashboard/property/boarding_room/boarding_room_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['total_boarding_rooms'] = self.get_queryset().count()
        context['search_form'] = BoardingRoomSearchForm(self.request.GET)

        context['create_boarding_house_form'] = CreateBoardingHouseForm(landlord=self.request.user)
        context['create_boarding_room_form'] = CreateBoardingRoomForm(landlord=self.request.user)
        context['update_boarding_house_form'] = CreateBoardingHouseForm(landlord=self.request.user)

        return context

    def get_queryset(self):
        queryset = super().get_queryset().order_by('-created_at')
        # current_url = resolve(self.request.path).url_name  # Get URL name

        queryset = queryset.filter(boarding_house__landlord=self.request.user)
        # Handle search query
        query = self.request.GET.get('query', '')
        search_by = self.request.GET.get('search_by', 'name')  # Default to 'name' if not specified
        if query:
            if search_by == 'name':
                queryset = queryset.filter(name__icontains=query)
            elif search_by == 'boarding_house':
                queryset = queryset.filter(boarding_house__name__icontains=query)

        # Handle sorting with direction (ascending or descending)
        sort_by = self.request.GET.get('sort', '')
        direction = self.request.GET.get('direction', 'asc')  # Default direction is ascending
        if sort_by:
            if sort_by == 'name':
                queryset = queryset.order_by(f"{'-' if direction == 'desc' else ''}name")
            elif sort_by == 'status':
                queryset = queryset.order_by(f"{'-' if direction == 'desc' else ''}is_available")
            elif sort_by == 'boarding_house':
                queryset = queryset.order_by(f"{'-' if direction == 'desc' else ''}boarding_house__name")
            elif sort_by == 'created_at':
                queryset = queryset.order_by(f"{'-' if direction == 'desc' else ''}created_at")
            elif sort_by == 'price':
                queryset = queryset.order_by(f"{'-' if direction == 'desc' else ''}price")

        return queryset

    def post(self, request, *args, **kwargs):
        self.object_list = self.get_queryset()
        context = self.get_context_data()

        # Handle deletion of a boarding house
        if 'delete-boarding_room' in request.POST:
            boarding_room_id = request.POST.get('delete-boarding_room')
            boarding_room = get_object_or_404(BoardingRoom, id=boarding_room_id)

            # Ensure only authorized users can delete
            if boarding_room.boarding_house.landlord != request.user:
                return HttpResponseForbidden("You are not allowed to delete this item.")

            messages.success(request, "Boarding room deleted successfully.")
            # Delete the boarding room
            boarding_room.delete()

        return self.render_to_response(context)


class BoardingHouseCreateView(CreateView):
    model = BoardingHouse
    form_class = CreateBoardingHouseForm
    template_name = 'property_management/dashboard/property/boarding_house/add_boarding_house.html'
    success_url = reverse_lazy('property_management:create-boarding-house')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['landlord'] = self.request.user
        return kwargs

    def form_valid(self, form):
        messages.success(self.request, "Boarding house created successfully.")
        return super().form_valid(form)


class BoardingRoomCreateView(CreateView):
    model = BoardingRoom
    form_class = CreateBoardingRoomForm
    template_name = 'property_management/dashboard/property/boarding_room/add_boarding_room.html'
    success_url = reverse_lazy('property_management:create-boarding-room')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['landlord'] = self.request.user
        return kwargs

    def form_valid(self, form):
        boarding_rooms = form.save(commit=True)
        self.object = boarding_rooms[0]  # Get the first boarding room created
        messages.success(self.request, f"{len(boarding_rooms)} Boarding room created successfully.")
        return HttpResponseRedirect(self.get_success_url())


class BoardingHouseUpdateView(UpdateView):
    model = BoardingHouse
    form_class = UpdateBoardingHouseForm
    template_name = 'property_management/dashboard/property/boarding_house/edit_boarding_house.html'
    context_object_name = 'boarding_house'

    def get_success_url(self):
        return reverse_lazy('property_management:update-boarding-house', kwargs={'pk': self.object.pk})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['existing_images'] = self.object.get_existing_images()
        return context

    def form_valid(self, form):
        messages.success(self.request, "Boarding house updated successfully.")

features/property_management/templates/property_management/dashboard/property/property_management.html
{% extends 'property_management/dashboard/base.html' %}
{% load widget_tweaks %}
{% load static %}
{% block title %}Dashboard - Boarding Houses{% endblock %}
{% block side_content %}
    <div class="h-full p-5">
        <div class="p-2">
            <h1 class="text-2xl font-semibold font-sans">Property Management</h1>
        </div>
        <div class="p-2 flex items-center justify-between flex-wrap">
            <button id="property-type-dropdown" data-dropdown-toggle="property-type-dropdown-menu"
                    data-dropdown-trigger="click"
                    class="text-white bg-[#319b94] hover:bg-[#277f7a] focus:ring-4 focus:ring-[#68c9c3] font-medium rounded-lg text-sm px-5 py-2.5 inline-flex items-center mb-2 sm:mb-0">
                Property Type
                <i class="ms-2 fa-solid fa-chevron-down"></i>
            </button>

            <!-- Dropdown menu -->
            <div id="property-type-dropdown-menu"
                 class="z-10 hidden bg-white divide-y divide-gray-100 rounded-lg shadow-md w-44">
                <ul class="py-2 text-sm text-gray-700 text-center">
                    <li>
                        <a href="{% url 'property_management:dashboard-boarding-houses' %}"
                           class="block px-4 py-2 hover:bg-gray-100">Boarding Houses</a>
                    </li>
                    <li>
                        <a href="{% url 'property_management:dashboard-boarding-rooms' %}"
                           class="block px-4 py-2 hover:bg-gray-100">Boarding Rooms</a>
                    </li>
                </ul>
            </div>

            <!-- Action Buttons -->
            <div class="space-x-2 flex flex-wrap">
                <a href="{% url 'property_management:create-boarding-room' %}"
                   class="rounded-lg bg-[#319b94] px-5 py-2.5 text-sm font-medium text-white hover:bg-[#277f7a] focus:ring-4 focus:ring-[#68c9c3] mb-2 sm:mb-0">
                    <i class="fa-solid fa-plus me-2"></i>
                    Add Room
                </a>
                <a href="{% url 'property_management:create-boarding-house' %}"
                   class="rounded-lg bg-[#319b94] px-5 py-2.5 text-sm font-medium text-white hover:bg-[#277f7a] focus:ring-4 focus:ring-[#68c9c3] mb-2 sm:mb-0">
                    <i class="fa-solid fa-plus me-2"></i>
                    Add Boarding House
                </a>
            </div>
        </div>

        <!-- Search Form -->
        <div class="p-2 mt-5" id="property-list">
            <form method="GET">
                <div class="flex flex-col sm:flex-row gap-x-5 gap-y-3">
                    <div class="relative w-full sm:w-96">
                        <button type="submit" class="absolute inset-y-0 left-0 flex items-center pl-3 text-gray-400">
                            <i class="fas fa-search"></i>
                        </button>
                        {{ search_form.query|add_class:"block w-full rounded-lg border border-gray-300 bg-gray-50 pl-10 py-2 text-sm text-gray-900 focus:ring-[#319b94] focus:border-[#319b94]"|attr:"placeholder:Search here" }}
                    </div>
                    <div class="w-full sm:w-48">
                        {{ search_form.search_by|add_class:"rounded-lg border border-gray-300 bg-gray-50 py-2 px-3 text-sm text-gray-900 focus:ring-[#319b94] focus:border-[#319b94]" }}
                    </div>
                </div>
            </form>

            <!-- Table Section -->
            <div id="table-container" class="relative overflow-x-auto mt-5 shadow-md rounded-lg">
                {% block table %}
                {% endblock %}
            </div>
        </div>
    </div>

    {% include 'html/modals/confirmation-modal.html' %}
    {% for message in messages %}
        {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
            {% include 'html/modals/success_modal.html' with message=message %}
        {% endif %}
    {% endfor %}
    <script type="module" src="{% static 'js/property_management.js' %}"></script>
{% endblock %}